# Generated by Django 3.0.3 on 2020-03-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
