# Generated by Django 3.0.3 on 2020-03-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createboard', '0002_img_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_board',
            name='description',
            field=models.TextField(),
        ),
    ]
