// Curated picks imported into content/prompts/open-sources.json.
//
// Only sources whose prompt text is redistributable are listed here:
// - f/awesome-chatgpt-prompts (prompts.chat): prompt data is CC0 1.0.
// - dair-ai/Prompt-Engineering-Guide: MIT License, (c) 2022 DAIR.AI.
//
// Row shape: [source title, 한국어 제목, 한 줄 설명, category, target, flags]
// category: dev | data | writing | learning | business | creative | life | image | prompting
// target:   chat (범용 챗봇) | agent (코딩 에이전트) | image (이미지 모델)
// flags:    "p" = editor pick, "u" = 이미지 업로드가 필요한 프롬프트

export const ACP_PICKS = [
  [
    "Ethereum Developer",
    "이더리움 스마트컨트랙트 개발자",
    "요구사항을 주면 Solidity 컨트랙트와 설계 설명을 함께 작성",
    "dev",
    "chat",
    "",
  ],
  [
    "Linux Terminal",
    "리눅스 터미널 시뮬레이터",
    "명령어를 입력하면 터미널 출력만 코드 블록으로 응답",
    "dev",
    "chat",
    "p",
  ],
  [
    "English Translator and Improver",
    "영어 번역·문장 다듬기",
    "어떤 언어로 쓰든 감지해서 더 세련된 영어 문장으로 고쳐 씀",
    "writing",
    "chat",
    "p",
  ],
  [
    "Job Interviewer",
    "모의 면접관",
    "직무를 알려주면 질문을 하나씩 던지며 답을 기다리는 면접 연습",
    "business",
    "chat",
    "p",
  ],
  [
    "JavaScript Console",
    "자바스크립트 콘솔",
    "JS 코드를 입력하면 콘솔 출력만 돌려줌",
    "dev",
    "chat",
    "",
  ],
  [
    "Excel Sheet",
    "텍스트 엑셀 시트",
    "행·열 표를 텍스트로 유지하며 입력한 수식의 결과를 보여줌",
    "data",
    "chat",
    "",
  ],
  [
    "Spoken English Teacher and Improver",
    "영어 회화 선생님",
    "대화를 이어가면서 문법·오타·표현을 바로 교정해 줌",
    "learning",
    "chat",
    "",
  ],
  [
    "Travel Guide",
    "여행 가이드",
    "현재 위치와 취향을 주면 근처에 가볼 곳을 추천",
    "life",
    "chat",
    "",
  ],
  [
    "Advertiser",
    "광고 캠페인 기획자",
    "제품과 타깃을 주면 메시지·채널·활동까지 캠페인을 설계",
    "business",
    "chat",
    "",
  ],
  [
    "Storyteller",
    "이야기꾼",
    "대상 연령과 주제에 맞춘 이야기를 지어 줌",
    "creative",
    "chat",
    "",
  ],
  [
    "Football Commentator",
    "축구 해설가",
    "경기 상황을 주면 중계 해설과 전술 분석을 곁들여 설명",
    "creative",
    "chat",
    "",
  ],
  [
    "Stand-up Comedian",
    "스탠드업 코미디언",
    "주제를 주면 생활 밀착형 코미디 루틴을 작성",
    "creative",
    "chat",
    "",
  ],
  [
    "Motivational Coach",
    "동기부여 코치",
    "목표와 고민을 주면 실천 가능한 전략과 확언을 제안",
    "life",
    "chat",
    "",
  ],
  [
    "Composer",
    "작곡가",
    "가사를 주면 어울리는 멜로디와 악기 구성을 설명",
    "creative",
    "chat",
    "",
  ],
  [
    "Debater",
    "토론자",
    "시사 주제의 찬반 논거와 반박 포인트를 정리",
    "writing",
    "chat",
    "",
  ],
  [
    "Debate Coach",
    "토론 코치",
    "토론 팀의 논증 구성·발표·반박 연습을 지도",
    "learning",
    "chat",
    "",
  ],
  [
    "Screenwriter",
    "시나리오 작가",
    "인물·배경·대사가 살아 있는 영화·웹시리즈 대본을 구상",
    "creative",
    "chat",
    "",
  ],
  [
    "Novelist",
    "소설가",
    "장르와 소재를 정하면 흡입력 있는 줄거리와 전개를 씀",
    "creative",
    "chat",
    "",
  ],
  [
    "Movie Critic",
    "영화 평론가",
    "줄거리·연기·연출·음악까지 짚는 영화 리뷰 작성",
    "writing",
    "chat",
    "",
  ],
  [
    "Relationship Coach",
    "관계 코치",
    "두 사람 사이의 갈등 상황에 소통 방법을 제안",
    "life",
    "chat",
    "",
  ],
  ["Poet", "시인", "주제를 주면 감정이 실린 시를 씀", "creative", "chat", ""],
  [
    "Rapper",
    "래퍼",
    "주제에 맞춘 랩 가사와 비트 아이디어를 만듦",
    "creative",
    "chat",
    "",
  ],
  [
    "Motivational Speaker",
    "동기부여 연사",
    "주제를 주면 청중을 움직이는 짧은 연설문을 작성",
    "writing",
    "chat",
    "",
  ],
  [
    "Philosophy Teacher",
    "철학 선생님",
    "철학 개념을 일상 예시로 쉽게 풀어 설명",
    "learning",
    "chat",
    "",
  ],
  [
    "Philosopher",
    "철학자",
    "철학적 질문을 깊게 탐구하고 윤리적 틀을 제안",
    "learning",
    "chat",
    "",
  ],
  [
    "Math Teacher",
    "수학 선생님",
    "수식과 개념을 단계별로 쉽게 설명",
    "learning",
    "chat",
    "",
  ],
  [
    "AI Writing Tutor",
    "글쓰기 튜터",
    "글을 주면 구조·논리·표현에 대한 피드백을 줌",
    "writing",
    "chat",
    "p",
  ],
  [
    "UX/UI Developer",
    "UX/UI 컨설턴트",
    "앱·웹 설계의 사용자 경험 개선안과 프로토타입 방향을 제시",
    "dev",
    "chat",
    "",
  ],
  [
    "Cyber Security Specialist",
    "보안 전문가",
    "데이터 보호 상황을 설명하면 방어 전략을 제안",
    "dev",
    "chat",
    "",
  ],
  [
    "Recruiter",
    "채용 담당자",
    "직무 조건을 주면 후보자 소싱 전략을 제안",
    "business",
    "chat",
    "",
  ],
  [
    "Life Coach",
    "라이프 코치",
    "현재 상황과 목표를 주면 더 나은 결정을 돕는 전략을 제시",
    "life",
    "chat",
    "",
  ],
  [
    "Etymologist",
    "어원 탐구가",
    "단어의 기원과 의미 변화를 추적해 설명",
    "learning",
    "chat",
    "",
  ],
  [
    "Commentariat",
    "칼럼니스트",
    "뉴스 주제에 대해 근거를 갖춘 의견 칼럼을 씀",
    "writing",
    "chat",
    "",
  ],
  [
    "Career Counselor",
    "진로 상담가",
    "관심사·기술·경험으로 맞는 진로를 함께 탐색",
    "business",
    "chat",
    "",
  ],
  [
    "Pet Behaviorist",
    "반려동물 행동 전문가",
    "반려동물 문제 행동의 원인과 교정 계획을 제안",
    "life",
    "chat",
    "",
  ],
  [
    "Real Estate Agent",
    "부동산 중개인",
    "예산·생활 방식·위치 조건으로 맞는 집을 함께 찾음",
    "life",
    "chat",
    "",
  ],
  [
    "Logistician",
    "행사 물류 담당",
    "행사 규모·장소를 주면 물류·안전 계획을 세움",
    "business",
    "chat",
    "",
  ],
  [
    "Web Design Consultant",
    "웹 디자인 컨설턴트",
    "사업 목표에 맞는 웹사이트 구조와 기술 스택을 제안",
    "dev",
    "chat",
    "",
  ],
  ["Chef", "셰프", "영양가 있고 간단한 레시피를 추천", "life", "chat", ""],
  [
    "Automobile Mechanic",
    "자동차 정비 상담",
    "증상을 설명하면 원인 진단과 점검 순서를 안내",
    "life",
    "chat",
    "",
  ],
  [
    "Artist Advisor",
    "미술 조언가",
    "스타일·기법 조언과 참고할 작품을 제안",
    "creative",
    "chat",
    "",
  ],
  [
    "Tea-Taster",
    "차 감별사",
    "차의 맛과 향을 전문가처럼 비교 평가",
    "life",
    "chat",
    "",
  ],
  [
    "Interior Decorator",
    "인테리어 디자이너",
    "공간 용도에 맞는 테마·배치·색 조합을 제안",
    "life",
    "chat",
    "",
  ],
  [
    "Florist",
    "플로리스트",
    "꽃 고르기와 오래가는 꽃꽂이 방법을 알려줌",
    "life",
    "chat",
    "",
  ],
  [
    "Self-Help Book",
    "자기계발서",
    "고민을 털어놓으면 자기계발서처럼 조언",
    "life",
    "chat",
    "",
  ],
  [
    "Gnomist",
    "소소한 놀거리 추천",
    "어디서든 할 수 있는 재미있는 활동을 제안",
    "life",
    "chat",
    "",
  ],
  [
    "Aphorism Book",
    "명언집",
    "상황에 맞는 명언과 실천 방법을 함께 제시",
    "life",
    "chat",
    "",
  ],
  [
    "Text Based Adventure Game",
    "텍스트 어드벤처 게임",
    "명령어를 입력하며 진행하는 텍스트 RPG",
    "creative",
    "chat",
    "p",
  ],
  [
    "Fancy Title Generator",
    "제목 생성기",
    "키워드를 주면 눈에 띄는 제목 후보를 만듦",
    "writing",
    "chat",
    "",
  ],
  [
    "Statistician",
    "통계 전문가",
    "통계 개념·가설검정·분포 관련 질문에 답변",
    "data",
    "chat",
    "",
  ],
  [
    "Prompt Generator",
    "프롬프트 생성기",
    "만들고 싶은 역할을 주면 'Act as' 형식의 프롬프트를 작성",
    "prompting",
    "chat",
    "p",
  ],
  [
    "Instructor in a School",
    "알고리즘 강사",
    "알고리즘을 파이썬 예제와 함께 초보자 눈높이로 설명",
    "learning",
    "chat",
    "",
  ],
  [
    "SQL Terminal",
    "SQL 터미널",
    "예시 DB에 쿼리를 입력하면 결과 표만 응답",
    "dev",
    "chat",
    "",
  ],
  [
    "Smart Domain Name Generator",
    "도메인 이름 생성기",
    "회사·아이디어 설명으로 짧고 기억에 남는 도메인 후보를 제안",
    "business",
    "chat",
    "",
  ],
  [
    "Tech Reviewer",
    "IT 제품 리뷰어",
    "기기의 장단점과 경쟁 제품 비교 리뷰를 작성",
    "writing",
    "chat",
    "",
  ],
  [
    "Developer Relations Consultant",
    "데브렐 컨설턴트",
    "패키지·문서·커뮤니티 지표로 DevRel 현황을 분석",
    "dev",
    "chat",
    "",
  ],
  [
    "Academician",
    "학술 연구자",
    "주제를 주면 출처를 갖춘 학술 글을 작성",
    "writing",
    "chat",
    "",
  ],
  [
    "IT Architect",
    "IT 아키텍트",
    "기존 IT 환경에 새 시스템을 통합하는 설계를 제안",
    "dev",
    "chat",
    "",
  ],
  [
    "Fallacy Finder",
    "논리 오류 탐지기",
    "주장 속 논리적 오류와 근거 부족을 짚어 줌",
    "writing",
    "chat",
    "p",
  ],
  [
    "Journal Reviewer",
    "논문 리뷰어",
    "논문 원고의 강점·약점을 심사위원처럼 평가",
    "writing",
    "chat",
    "p",
  ],
  [
    "DIY Expert",
    "DIY 전문가",
    "집수리·만들기 작업을 단계별로 안내",
    "life",
    "chat",
    "",
  ],
  [
    "Social Media Influencer",
    "SNS 인플루언서",
    "플랫폼별 콘텐츠와 캠페인을 기획",
    "business",
    "chat",
    "",
  ],
  [
    "Socrat",
    "소크라테스",
    "소크라테스식 문답으로 생각의 전제를 검증",
    "learning",
    "chat",
    "",
  ],
  [
    "Educational Content Creator",
    "교육 콘텐츠 제작자",
    "교안과 강의 자료 초안을 작성",
    "learning",
    "chat",
    "",
  ],
  [
    "Essay Writer",
    "에세이 작가",
    "주제에 대해 논지가 분명한 에세이를 씀",
    "writing",
    "chat",
    "",
  ],
  [
    "Social Media Manager",
    "소셜 미디어 매니저",
    "채널 운영·응대·성과 분석 전략을 세움",
    "business",
    "chat",
    "",
  ],
  [
    "Elocutionist",
    "스피치 연습 코치",
    "발성·억양·몸짓 등 말하기 기법을 연습",
    "learning",
    "chat",
    "",
  ],
  [
    "Scientific Data Visualizer",
    "과학 데이터 시각화",
    "데이터에 맞는 차트와 대시보드 구성을 설계",
    "data",
    "chat",
    "",
  ],
  [
    "Historian",
    "역사학자",
    "1차 사료를 바탕으로 역사적 사건을 분석",
    "learning",
    "chat",
    "",
  ],
  [
    "Journalist",
    "기자",
    "사실 확인과 보도 윤리를 지키는 기사를 작성",
    "writing",
    "chat",
    "",
  ],
  [
    "Digital Art Gallery Guide",
    "디지털 갤러리 큐레이터",
    "온라인 전시와 작품 감상 경로를 추천",
    "creative",
    "chat",
    "",
  ],
  [
    "Public Speaking Coach",
    "발표 코치",
    "청중을 사로잡는 발표 구성과 전달 방법을 연습",
    "learning",
    "chat",
    "",
  ],
  [
    "Makeup Artist",
    "메이크업 아티스트",
    "피부 타입과 상황에 맞는 메이크업을 제안",
    "life",
    "chat",
    "",
  ],
  [
    "Tech Writer",
    "테크니컬 라이터",
    "앱 기능을 단계별 사용 가이드 문서로 작성",
    "writing",
    "chat",
    "p",
  ],
  [
    "Ascii Artist",
    "ASCII 아티스트",
    "물체 이름을 주면 ASCII 아트로 그려 줌",
    "creative",
    "chat",
    "",
  ],
  [
    "Python Interpreter",
    "파이썬 인터프리터",
    "파이썬 코드를 주면 실행 결과만 응답",
    "dev",
    "chat",
    "",
  ],
  [
    "Synonym Finder",
    "유의어 찾기",
    "단어를 주면 바꿔 쓸 수 있는 유의어 목록을 제시",
    "writing",
    "chat",
    "",
  ],
  [
    "Personal Shopper",
    "퍼스널 쇼퍼",
    "예산과 취향으로 살 만한 물건을 추천",
    "life",
    "chat",
    "",
  ],
  [
    "Food Critic",
    "음식 평론가",
    "식당과 음식 경험을 리뷰로 정리",
    "writing",
    "chat",
    "",
  ],
  [
    "Personal Chef",
    "개인 셰프",
    "식습관과 선호에 맞춘 레시피를 제안",
    "life",
    "chat",
    "",
  ],
  [
    "Personal Stylist",
    "퍼스널 스타일리스트",
    "취향·상황별 코디를 제안",
    "life",
    "chat",
    "",
  ],
  [
    "Machine Learning Engineer",
    "머신러닝 엔지니어",
    "ML 개념을 설명하고 모델 구현 방향을 제안",
    "dev",
    "chat",
    "p",
  ],
  [
    "SVG designer",
    "SVG 디자이너",
    "설명을 주면 SVG 코드를 이미지로 바로 볼 수 있게 생성",
    "dev",
    "chat",
    "",
  ],
  [
    "IT Expert",
    "IT 해결사",
    "컴퓨터 문제를 단계별로 진단하고 해결",
    "dev",
    "chat",
    "",
  ],
  [
    "Chess Player",
    "체스 상대",
    "수를 주고받으며 체스 대국을 진행",
    "creative",
    "chat",
    "",
  ],
  [
    "Midjourney Prompt Generator",
    "Midjourney 프롬프트 생성기",
    "짧은 아이디어를 상세하고 상상력 있는 이미지 프롬프트로 확장",
    "image",
    "chat",
    "",
  ],
  [
    "Fullstack Software Developer",
    "풀스택 개발자",
    "요구사항으로 웹앱 아키텍처와 코드를 설계",
    "dev",
    "chat",
    "",
  ],
  [
    "Mathematician",
    "계산기 수학자",
    "수식을 주면 계산 결과만 응답",
    "data",
    "chat",
    "",
  ],
  [
    "RegEx Generator",
    "정규식 생성기",
    "패턴 설명을 주면 정규표현식만 출력",
    "dev",
    "chat",
    "p",
  ],
  [
    "Time Travel Guide",
    "시간 여행 가이드",
    "가고 싶은 시대의 볼거리와 체험을 추천",
    "creative",
    "chat",
    "",
  ],
  [
    "Talent Coach",
    "면접 준비 코치",
    "직무명을 주면 필요 역량과 예상 질문을 정리",
    "business",
    "chat",
    "",
  ],
  [
    "R Programming Interpreter",
    "R 인터프리터",
    "R 코드를 주면 실행 결과만 응답",
    "dev",
    "chat",
    "",
  ],
  [
    "StackOverflow Post",
    "스택오버플로 답변",
    "프로그래밍 질문에 답변 코드 중심으로 응답",
    "dev",
    "chat",
    "",
  ],
  [
    "Emoji Translator",
    "이모지 번역기",
    "문장을 이모지로만 표현",
    "creative",
    "chat",
    "",
  ],
  [
    "PHP Interpreter",
    "PHP 인터프리터",
    "PHP 코드를 주면 실행 결과만 응답",
    "dev",
    "chat",
    "",
  ],
  [
    "Fill in the Blank Worksheets Generator",
    "빈칸 채우기 학습지",
    "영어 학습자용 빈칸 문제와 보기를 생성",
    "learning",
    "chat",
    "",
  ],
  [
    "Software Quality Assurance Tester",
    "QA 테스터",
    "기능을 테스트하고 재현 절차가 담긴 버그 리포트를 작성",
    "dev",
    "chat",
    "",
  ],
  [
    "Tic-Tac-Toe Game",
    "틱택토 게임",
    "보드를 갱신하며 틱택토 대결을 진행",
    "creative",
    "chat",
    "",
  ],
  [
    "New Language Creator",
    "가상 언어 창조자",
    "문장을 새로 만든 가상 언어로 번역",
    "creative",
    "chat",
    "",
  ],
  [
    "Web Browser",
    "텍스트 웹 브라우저",
    "가상의 웹 페이지를 텍스트로 탐색",
    "creative",
    "chat",
    "",
  ],
  [
    "Senior Frontend Developer",
    "시니어 프론트엔드 개발자",
    "요구사항으로 React 프로젝트 코드를 작성",
    "dev",
    "chat",
    "",
  ],
  [
    "Code Reviewer",
    "코드 리뷰어",
    "코드의 품질·보안·성능 개선점을 짚어 줌",
    "dev",
    "chat",
    "p",
  ],
  [
    "Accessibility Auditor",
    "접근성 감사관",
    "웹 접근성(WCAG) 문제와 개선안을 점검",
    "dev",
    "chat",
    "",
  ],
  [
    "Solr Search Engine",
    "Solr 검색엔진",
    "JSON 문서 색인과 검색 쿼리를 흉내 냄",
    "dev",
    "chat",
    "",
  ],
  [
    "Startup Idea Generator",
    "스타트업 아이디어 생성기",
    "불편함을 주면 사업 계획 요소를 표로 정리",
    "business",
    "chat",
    "",
  ],
  [
    "Language Detector",
    "언어 감지기",
    "입력 문장이 어떤 언어인지 판별",
    "writing",
    "chat",
    "",
  ],
  [
    "Salesperson",
    "세일즈 롤플레이",
    "무엇이든 팔아 보는 영업 대화 연습",
    "business",
    "chat",
    "",
  ],
  [
    "Commit Message Generator",
    "커밋 메시지 생성기",
    "작업 내용을 주면 간결한 커밋 메시지 한 줄",
    "dev",
    "chat",
    "",
  ],
  [
    "Conventional Commit Message Generator",
    "Conventional Commit 생성기",
    "변경 내용을 Conventional Commits 규격 메시지로 변환",
    "dev",
    "chat",
    "p",
  ],
  [
    "Chief Executive Officer",
    "CEO 롤플레이",
    "위기 상황의 의사결정을 경영자 관점에서 연습",
    "business",
    "chat",
    "",
  ],
  [
    "Diagram Generator",
    "다이어그램 생성기",
    "설명을 Graphviz DOT 다이어그램 코드로 변환",
    "dev",
    "chat",
    "",
  ],
  [
    "Title Generator for written pieces",
    "글 제목 생성기",
    "글의 주제와 키워드로 제목 후보 5개를 제안",
    "writing",
    "chat",
    "",
  ],
  [
    "Product Manager",
    "프로덕트 매니저",
    "PRD를 섹션별로 함께 작성",
    "business",
    "chat",
    "p",
  ],
  [
    "Project Manager",
    "프로젝트 매니저",
    "일정·리스크·자원 관리 계획을 세움",
    "business",
    "chat",
    "",
  ],
  [
    "Mathematical History Teacher",
    "수학사 선생님",
    "수학 개념이 발전해 온 역사를 설명",
    "learning",
    "chat",
    "",
  ],
  [
    "Song Recommender",
    "노래 추천",
    "곡 하나를 주면 분위기가 비슷한 플레이리스트를 구성",
    "life",
    "chat",
    "",
  ],
  [
    "Cover Letter",
    "커버레터 작성",
    "경력과 기술을 주면 지원서 커버레터를 작성",
    "business",
    "chat",
    "",
  ],
  [
    "Technology Transferer",
    "이력서 기술 스택 변환",
    "이력서 bullet을 다른 기술 스택 기준으로 바꿔 씀",
    "business",
    "chat",
    "",
  ],
  [
    "Gomoku player",
    "오목 상대",
    "보드를 갱신하며 오목 대결을 진행",
    "creative",
    "chat",
    "",
  ],
  [
    "Proofreader",
    "교정 전문가",
    "글의 맞춤법·문법·문장 흐름을 교정",
    "writing",
    "chat",
    "",
  ],
  [
    "Chemical Reactor",
    "화학 반응기 시뮬레이터",
    "물질을 넣을 때마다 반응 결과를 기록",
    "creative",
    "chat",
    "",
  ],
  [
    "ChatGPT Prompt Generator",
    "프롬프트 생성기 (간단판)",
    "주제를 주면 역할형 프롬프트를 바로 작성",
    "prompting",
    "chat",
    "",
  ],
  [
    "Wikipedia Page",
    "위키백과 문서",
    "주제를 위키백과 문서 형식으로 요약",
    "writing",
    "chat",
    "",
  ],
  [
    "Japanese Kanji quiz machine",
    "일본어 한자 퀴즈",
    "JLPT 레벨별 한자 객관식 퀴즈를 출제",
    "learning",
    "chat",
    "",
  ],
  [
    "Note-Taking assistant",
    "강의 노트 정리",
    "강의 내용을 시험 대비 노트로 정리",
    "learning",
    "chat",
    "",
  ],
  [
    "Literary Critic",
    "문학 비평가",
    "작품의 장르·주제·구조를 분석",
    "writing",
    "chat",
    "",
  ],
  [
    "Prompt Enhancer",
    "프롬프트 강화기",
    "짧은 프롬프트를 구체적이고 효과적인 형태로 보강",
    "prompting",
    "chat",
    "p",
  ],
  [
    "Cheap Travel Ticket Advisor",
    "저렴한 항공권 조언",
    "출발지·목적지·일정으로 비용을 줄이는 방법을 제안",
    "life",
    "chat",
    "",
  ],
  [
    "Data Scientist",
    "데이터 사이언티스트",
    "데이터셋 분석 방향과 방법을 제안",
    "data",
    "chat",
    "",
  ],
  [
    "Restaurant Owner",
    "식당 창업 컨설턴트",
    "콘셉트·메뉴·인테리어를 기획",
    "business",
    "chat",
    "",
  ],
  [
    "Architectural Expert",
    "건축 전문가",
    "건축 설계·구조·시공 관련 질문에 상담",
    "life",
    "chat",
    "",
  ],
  [
    "LLM Researcher",
    "LLM 연구자",
    "논문과 기법을 쉽게 풀어 설명하고 실험 방향을 제안",
    "dev",
    "chat",
    "",
  ],
  [
    "Unit Tester Assistant",
    "단위 테스트 도우미",
    "코드를 주면 단위 테스트 케이스를 작성",
    "dev",
    "chat",
    "",
  ],
  [
    "Wisdom Generator",
    "지혜 생성기",
    "고전의 지혜를 지금의 상황에 연결",
    "life",
    "chat",
    "",
  ],
  [
    "YouTube Video Analyst",
    "유튜브 영상 분석가",
    "영상 내용과 구성을 분석하고 요약",
    "business",
    "chat",
    "",
  ],
  [
    "Career Coach",
    "커리어 코치",
    "이직과 성장 전략을 상담",
    "business",
    "chat",
    "",
  ],
  [
    "Acoustic Guitar Composer",
    "어쿠스틱 기타 작곡",
    "분위기에 맞는 기타 코드 진행과 곡 구성을 제안",
    "creative",
    "chat",
    "",
  ],
  [
    "Knowledgeable Software Development Mentor",
    "소프트웨어 개발 멘토",
    "설계 원칙과 코드 품질을 멘토처럼 지도",
    "dev",
    "chat",
    "",
  ],
  [
    "Logic Builder Tool",
    "로직 빌더",
    "문제를 푸는 알고리즘 사고 과정을 단계별로 안내",
    "dev",
    "chat",
    "",
  ],
  [
    "Guessing Game Master",
    "스무고개 게임",
    "질문으로 정답을 좁혀 가는 추리 게임 진행",
    "creative",
    "chat",
    "",
  ],
  [
    "Teacher of React.js",
    "React 선생님",
    "React 개념을 예제 중심으로 가르침",
    "dev",
    "chat",
    "",
  ],
  [
    "GitHub Expert",
    "GitHub 전문가",
    "Git·GitHub 사용법 질문에 답변",
    "dev",
    "chat",
    "",
  ],
  [
    "Any Programming Language to Python Converter",
    "파이썬 변환기",
    "다른 언어 코드를 파이썬으로 변환",
    "dev",
    "chat",
    "",
  ],
  [
    "DAX Terminal",
    "DAX 터미널",
    "Power BI DAX 식의 계산 결과를 흉내 냄",
    "data",
    "chat",
    "",
  ],
  [
    "Structured Iterative Reasoning Protocol (SIRP)",
    "구조적 반복 추론 프로토콜",
    "문제를 분해·검증하며 단계적으로 추론하게 하는 틀",
    "prompting",
    "chat",
    "",
  ],
  [
    "LinkedIn Ghostwriter",
    "링크드인 대필",
    "주제를 주면 링크드인 게시물을 작성",
    "business",
    "chat",
    "",
  ],
  [
    "Idea Clarifier GPT",
    "아이디어 구체화",
    "막연한 아이디어를 질문으로 다듬어 구체화",
    "business",
    "chat",
    "p",
  ],
  [
    "Top Programming Expert",
    "프로그래밍 전문가",
    "정확하고 간결한 코드 중심 답변",
    "dev",
    "chat",
    "",
  ],
  [
    "Architect Guide for Programmers",
    "프로그래머를 위한 아키텍처 가이드",
    "시스템 설계 원칙과 패턴을 단계별로 안내",
    "dev",
    "chat",
    "",
  ],
  [
    "Children's Book Creator",
    "동화책 작가",
    "아이 눈높이의 그림책 이야기를 만듦",
    "creative",
    "chat",
    "",
  ],
  [
    "Tech-Challenged Customer",
    "IT에 서툰 고객 롤플레이",
    "고객지원 응대 연습을 위한 가상 고객",
    "business",
    "chat",
    "",
  ],
  [
    "Creative Branding Strategist",
    "브랜딩 전략가",
    "브랜드 정체성과 메시지 전략을 설계",
    "business",
    "chat",
    "",
  ],
  [
    "Book Summarizer",
    "책 요약가",
    "책의 핵심 내용과 교훈을 요약",
    "writing",
    "chat",
    "",
  ],
  [
    "Study planner",
    "공부 계획표",
    "목표와 기간으로 학습 계획을 세움",
    "learning",
    "chat",
    "",
  ],
  [
    "SEO specialist",
    "SEO 전문가",
    "키워드·구조·콘텐츠 관점의 검색 최적화 전략",
    "business",
    "chat",
    "",
  ],
  [
    "Large Language Models Security Specialist",
    "LLM 보안 점검",
    "프롬프트 인젝션 등 LLM 취약점을 분석",
    "dev",
    "chat",
    "",
  ],
  [
    "Tech Troubleshooter",
    "기술 문제 해결사",
    "기기·소프트웨어 문제를 진단 단계별로 해결",
    "dev",
    "chat",
    "",
  ],
  [
    "Devops Engineer",
    "DevOps 엔지니어",
    "배포·인프라·CI/CD 문제를 해결하는 변수 템플릿",
    "dev",
    "chat",
    "",
  ],
  [
    "Linux Script Developer",
    "Bash 스크립트 개발자",
    "오류 처리와 도움말을 갖춘 Bash 스크립트를 작성",
    "dev",
    "agent",
    "",
  ],
  [
    "Reverse Prompt Engineer",
    "역방향 프롬프트 엔지니어",
    "결과물을 보고 그것을 만든 원래 프롬프트를 복원",
    "prompting",
    "chat",
    "p",
  ],
  [
    "Code Review Assistant",
    "코드 리뷰 어시스턴트",
    "가독성·버그·개선점·보안까지 항목별 상세 리뷰",
    "dev",
    "agent",
    "",
  ],
  [
    "Data Transformer",
    "데이터 변환기 (JSON)",
    "입출력 스키마를 정의해 데이터를 변환하는 구조화 프롬프트",
    "data",
    "chat",
    "",
  ],
  [
    "Continue Coding Assistant",
    "이어서 코딩하기",
    "기존 코드베이스를 파악하고 다음 작업을 이어감",
    "dev",
    "agent",
    "",
  ],
  [
    "Code Translator: Any Language to Any Language",
    "코드 언어 변환기",
    "원본·대상 언어를 지정해 주석과 함께 코드 변환",
    "dev",
    "agent",
    "",
  ],
  [
    "Developer Work Analysis from Git Diff and Commit Message",
    "Git diff 작업 분석",
    "diff와 커밋 메시지로 작업 범위와 품질을 평가",
    "dev",
    "agent",
    "",
  ],
  [
    "Coding Structure with MVC and SOLID Principles",
    "MVC·SOLID 구조 설계",
    "코드베이스를 MVC와 SOLID 원칙에 맞게 구조화",
    "dev",
    "agent",
    "",
  ],
  [
    "Bug Discovery Code Assistant",
    "버그 탐지 도우미",
    "코드에서 잠재 버그와 비효율을 찾아 수정안 제시",
    "dev",
    "agent",
    "",
  ],
  [
    "Sentry Bug Fixer",
    "Sentry 버그 수정",
    "Sentry 리포트로 원인을 분석하고 수정",
    "dev",
    "agent",
    "",
  ],
  [
    "Code Recon",
    "코드 정찰 (Code Recon)",
    "소스 코드의 구조·로직·성숙도를 종합 분석",
    "dev",
    "agent",
    "p",
  ],
  [
    "PRD",
    "PRD 공동 작성",
    "명확화 질문부터 시작해 제품 요구사항 문서를 작성",
    "business",
    "chat",
    "p",
  ],
  [
    "Small Functional Analyst mode",
    "기능 분석가 모드",
    "가정을 명시하고 범위를 통제하는 요구사항 분석",
    "business",
    "chat",
    "",
  ],
  [
    "Git Repository Analysis and Knowledge Base Construction",
    "Git 저장소 분석",
    "저장소 이력과 구조로 지식 베이스를 구축",
    "dev",
    "agent",
    "",
  ],
  [
    "Senior AI & Data Engineering Meta-Prompt Generator",
    "AI·데이터 엔지니어링 메타 프롬프트",
    "플랫폼과 목표를 받아 전문가용 프롬프트를 생성",
    "prompting",
    "chat",
    "",
  ],
  [
    "Predictive Eye Tracking Heatmap Generator",
    "시선 추적 히트맵 예측",
    "UI 화면의 주목 영역을 UX 관점에서 예측",
    "data",
    "chat",
    "u",
  ],
  [
    "⚙️ PromptForge",
    "PromptForge 프롬프트 검증",
    "프롬프트를 명확성·견고성 기준으로 분석하고 최적화",
    "prompting",
    "chat",
    "p",
  ],
  [
    "The Silent Standoff",
    "침묵의 대치 (2D 카툰)",
    "탑다운 구도의 긴장감 있는 2D 애니메이션 장면",
    "image",
    "image",
    "",
  ],
  [
    "Lifestyle Product Images",
    "제품 라이프스타일 컷",
    "업로드한 제품 사진으로 실제 사용 장면을 연출",
    "image",
    "image",
    "u",
  ],
  [
    "Isometric 3D Weather Cityscapes (PBR Textures)",
    "날씨를 담은 아이소메트릭 도시",
    "도시 이름으로 랜드마크와 현재 날씨가 담긴 미니어처",
    "image",
    "image",
    "p",
  ],
  [
    "World Landmarks: Hyper-Realistic 3D Dioramas",
    "랜드마크 3D 디오라마",
    "단면 지형 위에 올린 초사실 미니어처 모형",
    "image",
    "image",
    "",
  ],
  [
    "3D Isometric Miniature Diorama",
    "영화 대사 → 미니어처 디오라마",
    "대사를 주면 그 장면을 틸트시프트 디오라마로 표현",
    "image",
    "image",
    "",
  ],
  [
    "Architectural Sketch & Markup Overlay",
    "건축 스케치 오버레이",
    "사진 위에 건축가의 손그림 주석과 치수선을 덧입힘",
    "image",
    "image",
    "u",
  ],
  [
    "Floating City Island - Photoreal 4K Poster",
    "떠 있는 도시 섬 포스터",
    "도시 실루엣 모양 섬 위에 명소를 모은 포스터",
    "image",
    "image",
    "",
  ],
  [
    "Realistic Food Image Generator",
    "메뉴판용 음식 사진",
    "음식 이름으로 배달앱·메뉴판용 사실적인 사진",
    "image",
    "image",
    "",
  ],
  [
    "Urban Casual Confidence",
    "도시 캐주얼 인물 사진",
    "골든아워 거리 스냅 스타일의 인물 사진",
    "image",
    "image",
    "u",
  ],
  [
    "Double Exposure Portrait",
    "이중노출 초상",
    "옆얼굴 실루엣 안을 풍경으로 채운 이중노출",
    "image",
    "image",
    "",
  ],
  [
    "Time Layer Photography",
    "시간 레이어 사진",
    "한 장소의 여러 시대가 겹쳐 흐르는 사진",
    "image",
    "image",
    "",
  ],
  [
    "A Clay-Crafted City: Mini [CITY NAME] World",
    "점토 미니어처 도시",
    "랜드마크를 손으로 빚은 점토 세계로 표현",
    "image",
    "image",
    "",
  ],
  [
    "Architectural Study Sheet: [HISTORIC_SITE_NAME]",
    "건축 스터디 시트",
    "유적의 입면도·치수·디테일을 담은 빈티지 인포그래픽",
    "image",
    "image",
    "",
  ],
  [
    "Clean Clinic Portrait",
    "클리닉 인물 컷",
    "업로드한 인물을 밝은 치과 진료실 장면에 배치",
    "image",
    "image",
    "u",
  ],
  [
    "Hyper-Realistic Clay Bust From Photo Template",
    "점토 흉상 만들기",
    "사진 속 인물을 수제 점토 흉상 조각으로 변환",
    "image",
    "image",
    "pu",
  ],
  [
    "Ultra-Realistic Noir Portrait Creation",
    "누아르 흑백 초상",
    "셀카를 하이콘트라스트 흑백 초상으로 변환",
    "image",
    "image",
    "u",
  ],
  [
    "Christmas Poster - Festive Holiday Scene",
    "크리스마스 포스터",
    "따뜻한 연말 분위기의 SNS용 정사각 포스터",
    "image",
    "image",
    "",
  ],
];

// Prompt Engineering Guide example pages (pages/prompts/<path>.en.mdx).
// Row shape: [path, 한국어 제목, 한 줄 설명, category, flags]
export const DAIR_PICKS = [
  [
    "classification/sentiment",
    "감정 분류 (제로샷)",
    "텍스트를 긍정·부정·중립으로 분류하는 기본 템플릿",
    "data",
    "",
  ],
  [
    "classification/sentiment-fewshot",
    "감정 분류 (퓨샷)",
    "라벨이 무작위여도 예시 형식만으로 출력을 맞추는 퓨샷 실험",
    "data",
    "",
  ],
  [
    "coding/code-snippet",
    "주석 → 코드 생성",
    "주석으로 설명한 동작을 코드 스니펫으로 생성",
    "dev",
    "",
  ],
  [
    "coding/mysql-query",
    "자연어 → MySQL 쿼리",
    "테이블 스키마와 요청을 주고 SQL을 작성하게 함",
    "dev",
    "p",
  ],
  [
    "coding/tikz",
    "TikZ 그림 그리기",
    "LaTeX TikZ 코드로 그림을 그리게 하는 예시",
    "dev",
    "",
  ],
  [
    "creativity/infinite-primes",
    "시로 쓰는 증명",
    "소수가 무한하다는 증명을 희곡 형식으로 풀어 씀",
    "creative",
    "",
  ],
  [
    "creativity/interdisciplinary",
    "학제 간 글쓰기",
    "서로 다른 분야를 엮어 창의적인 글을 쓰게 함",
    "creative",
    "",
  ],
  [
    "creativity/new-words",
    "신조어 예문 만들기",
    "새 단어의 정의를 주고 자연스러운 예문을 생성",
    "creative",
    "",
  ],
  [
    "creativity/rhymes",
    "운율 있는 증명",
    "수학 증명을 운율 있는 시로 표현",
    "creative",
    "",
  ],
  [
    "evaluation/plato-dialogue",
    "플라톤식 대화 평가",
    "두 모델의 출력을 비교 평가하게 하는 예시",
    "prompting",
    "",
  ],
  [
    "image-generation/alphabet-person",
    "알파벳으로 사람 그리기",
    "글자 모양을 조합해 사람을 그리는 코드 생성",
    "creative",
    "",
  ],
  [
    "information-extraction/extract-models",
    "초록에서 모델명 추출",
    "논문 초록 속 LLM 이름을 JSON 배열로 추출",
    "data",
    "p",
  ],
  [
    "mathematics/odd-numbers",
    "홀수 합 검증",
    "문제를 단계별로 풀고 결론을 확인하게 하는 추론 예시",
    "learning",
    "",
  ],
  [
    "question-answering/closed-domain",
    "폐쇄형 도메인 QA",
    "주어진 정보 안에서만 답하도록 제한",
    "prompting",
    "",
  ],
  [
    "question-answering/open-domain",
    "개방형 QA",
    "모르면 모른다고 답하게 하는 일반 질의응답",
    "prompting",
    "",
  ],
  [
    "question-answering/science-qa",
    "근거 문단 기반 과학 QA",
    "참고 문단을 주고 그 안에서만 답하는 RAG형 템플릿",
    "prompting",
    "p",
  ],
  [
    "reasoning/indirect-reasoning",
    "간접 추론",
    "귀류법 등 간접 증명 방식으로 추론",
    "prompting",
    "",
  ],
  [
    "reasoning/physical-reasoning",
    "물리 상식 추론",
    "물체를 안정적으로 쌓는 방법을 추론",
    "prompting",
    "",
  ],
  [
    "text-summarization/explain-concept",
    "개념 쉽게 설명하기",
    "개념을 짧고 쉽게 요약 설명",
    "writing",
    "",
  ],
  [
    "truthfulness/identify-hallucination",
    "환각 탐지",
    "근거와 대조해 답변의 환각 여부를 판단",
    "prompting",
    "p",
  ],
  [
    "adversarial-prompting/prompt-injection",
    "프롬프트 인젝션 테스트",
    "번역 지시를 무시하게 만드는 인젝션 예시 (방어 테스트용)",
    "dev",
    "",
  ],
  [
    "adversarial-prompting/prompt-leaking",
    "프롬프트 유출 테스트",
    "시스템 지시문 유출을 유도하는 예시 (방어 테스트용)",
    "dev",
    "",
  ],
];
